Week 2 step 2
michaellawes/software-product-sprint pull request #5
Opened 2021-03-03 03:46 UTC by michaellawes

Add fetch() functionality to page with button and javascript function in script.js to dynamically server HTML

2021-03-03 16:03 UTC, andiov commented on portfolio/src/main/webapp/index.html
> +      <button onclick="showWeek2();">
You don't need ;

2021-03-03 16:03 UTC, andiov commented on portfolio/src/main/webapp/index.html
> +      <p id="week-2-container"></p>
In general, try and keep the id names related to the project itself not weeks.

2021-03-03 16:35 UTC, sarahrittgers26 requested changes

2021-03-03 16:35 UTC, sarahrittgers26 commented on portfolio/src/main/webapp/script.js
> +	  week2Container.innerText = textFromResponse;
Can you fix the indentation?

2021-03-03 16:45 UTC, michaellawes reviewed
I made the requested changes to the files, should I make a new branch and submit another pull request?

2021-03-03 17:09 UTC, andiov approved these changes

2021-03-03 17:10 UTC, andiov commented
In general, you want to reply to each comment on your change to say whether you've addressed the issue or why not. Once that happens, we review and approve or leave more comments. You do not need to create a new PR.

2021-03-03 17:53 UTC, michaellawes commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Ok understood thank you   From: andiovSent: Wednesday, March 3, 2021 12:10 PMTo: michaellawes/software-product-sprintCc: michaellawes; AuthorSubject: Re: [michaellawes/software-product-sprint] Week 2 step 2 (#5) In general, you want to reply to each comment on your change to say whether you've addressed the issue or why not. Once that happens, we review and approve or leave more comments. You do not need to create a new PR.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

2021-03-03 18:26 UTC, michaellawes reviewed
Completed week 2 step 2

2021-03-04 16:47 UTC, sarahrittgers26 approved these changes

2021-03-04 19:46 UTC, merged